config/routes.rb
Stackoverthrow::Application.routes.draw do
  root :to => "questions#index"
  resources :questions do
    resources :answers, except: [:index, :show]
  end

  resources :users, only: [:show, :create, :new, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  resources :questions, only: [:create, :destroy] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :new]
  end

  resources :answers, only: [:create, :destroy] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :new]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :text, :vote_count
  validates :text, :question_id, :user_id, :presence => true
  belongs_to :question
  belongs_to :user
  has_many :votes, :as => :votable
  has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :commentable_id, :commentable_type, :opinion
  validates :opinion, :presence => true
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :text, :vote_count
  validates :title, :text, :user_id, :presence => true
  belongs_to :user
  has_many :answers
  has_many :votes, as: :votable
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :username, :password, :password_confirmation, :reputation
  validates_presence_of :username
  has_many :questions
  has_many :answers
  has_many :votes

  def update_reputation(vote)
  	self.reputation += vote.up_down
  	self.save
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :up_down, :votable_id, :votable_type, :user_id
  validates :up_down, :presence => true
  belongs_to :votable, polymorphic: true
  belongs_to :user

  def get_redirect_path(votable)
    if votable.class.name == "Question"
      votable
    else
      votable.question
    end
  end

  def update_votable_count(votable, up_or_down)
    votable.vote_count += up_or_down
    votable.save
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :load_question

  def new
    @answer = Answer.new
  end

  def create
    if logged_in?
      @answer = @question.answers.new params[:answer]

      unless (current_user.answers << @answer) && (@question.answers << @answer)
        render(:new) && return
      end

      redirect_to(question_path(@question)) && return
    end

    redirect_to new_user_path, flash: {errors: "Not logged in"}
  end

  def edit
    load_answer
  end

  def update
    load_answer

    unless @answer.update_attributes(params[:answer]) && current_user.id == @answer.user_id
      render(:edit) && return
    end

    redirect_to(question_path(@question)) && return
  end

  def destroy
    load_answer
    @answer.destroy
    redirect_to(question_path(@question))
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def logged_in?
    !!session[:id]
  end

  def current_user
    User.find(session[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@commentable = load_commentable
		@comment = Comment.new
	end

	def create
		@commentable = load_commentable
		@comment = @commentable.comments.build(params[:comment])
		@comment.user_id=session[:id]
		if @comment.save
			flash[:notice] = "Successfully created comment."
			if @commentable.class.name == "Answer"
				redirect_to @commentable.question
			else
				redirect_to @commentable
			end
		else
			render :action => 'new'
		end
	end

	private

	def load_commentable
    	params.each do |name, value|
			return $1.classify.constantize.find(value) if name =~ /(.+)_id$/
		end
  	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    if params[:search]
      @questions = Question.where("title like ?", "%#{params[:search]}%")
    else
      @questions = Question.all.sort! {|a,b| b.vote_count <=>  a.vote_count}
    end
  end

  def new
    @question = Question.new
  end

  def create
    if logged_in?
      @question = current_user.questions.new params[:question]

      render(:new) && return unless (current_user.questions << @question)
      redirect_to(root_path) && return
    end

    redirect_to new_user_path, flash: {errors: "Not logged in"}
  end

  def show
    load_question
    @votable = @question
    @answers = @question.answers.sort! {|a,b| b.vote_count <=>  a.vote_count}
    @votes = @votable.votes
  end

  def edit
    load_question
  end

  def update
    load_question

    unless @question.update_attributes(params[:question]) && @question.user_id == current_user.id
      render(:edit) && return
    end
    redirect_to(question_path(@question)) && return
  end

  def destroy
    load_question
    @question.destroy
    redirect_to(root_path)
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      session[:id] = @user.id
      redirect_to root_path
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    redirect_to user_path(session[:id]) unless !session[:id]
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:id] = @user.id
      redirect_to root_path
    else
      render 'users/new'
    end
  end

  def show

    redirect_to new_user_path unless session[:id]
    @user = User.find(params[:id])
    @votes = Vote.where(user_id: @user.id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    load_votable
    redirect_to(new_user_path) && return unless logged_in?
    @vote = Vote.new
    path = @vote.get_redirect_path(@votable)
    redirect_to(path) && return if @votable.votes.find_by_user_id(current_user.id)

    up_or_down = params[:up_down].to_i
    @vote = @votable.votes.create(user_id: current_user.id, up_down: up_or_down)

    @votable.user.update_reputation(@vote)
    @vote.update_votable_count(@votable, up_or_down)
    redirect_to(path)
  end

  private

  def load_votable
    klass = [Question, Answer].detect { |v| params["#{v.name.underscore}_id"]}
    @votable = klass.find(params["#{klass.name.underscore}_id"])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/answers/_answer.html.erb
<div class="answersContainer">
  <ul class="answers">
    <% @answers.each do |answer| %>
      <li class="single_ans">
        <ul class="edit_buttons">
            <li>
              <%= render partial: 'votes/vote', locals: { votable: answer } %>
            </li>
            <li>
              <span class="question_user">Answered by: <span class="user"><%= link_to answer.user.username, user_path(answer.user) %></span></span>
            </li>
              <% if !!session[:id] && (session[:id] == answer.user_id) %>
              <li>
                <%= button_to "Edit", edit_question_answer_path( @question, answer ), :method => :get %>
              </li>
              <li>
                <%= button_to "Delete", question_answer_path( @question, answer ), :method => :delete %>
              </li>
            <% end %>
            <li>
              <span class="comment_button"><%= button_to "comment", new_answer_comment_path(answer), {:method => :get, remote: true, :class => "commentButton"} %></span>
            <li>

          </ul>
          <h5><%= answer.text %></h5>

        <%= render partial: 'shared/comments', locals: {commentable: answer} %>
      </li>
    <% end %>
  </ul>
</div>

app/views/answers/_form.html.erb
<div class="answerForm ask_answer">
  <ul class="answer_form_list">
    <%= form_for [@question, @answer] do |f| %>
      <li class="text_input"><h4><%= f.label :text  %>
      <%= f.text_area :text  %></h4></li>
      <li class="text_submit"><%= f.submit "Answer", :class => "submitAnswer" %></li>
    <% end %>
  </ul>
</div>

app/views/answers/edit.html.erb
<%= render 'shared/errors', :object => @question, :object => @answer  %>
<%= render 'form', :object => @question, :object => @answer  %>

app/views/answers/new.html.erb
<%= render 'shared/errors', :object => @answer %>
<%= render 'form', :object => @answer, :object => @question %>

app/views/comments/new.html.erb
<div class= "commentForm ask_answer">
	<%= form_for [@commentable, @comment] do |f| %>
		<%= f.label :opinion%>
		<%= f.text_area :opinion%>
		<%= f.submit 'comment', class: "submitComment" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackoverthrow</title>
  <%= stylesheet_link_tag    "application", "style", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="navbar">
    <h1><a href="/">STACKOVERTHROW</a></h1>

    <ul>

      <li><%= form_tag questions_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
      <% end %></li>
      <li><a href="/">Home</a></li>
      <li><%= render 'shared/login:logout' %></li>



    </ul>
  </div>

  <div id="content_field">
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<div class= "ask_answer">
  <ul>
    <%= form_for @question do |f| %>
      <li class="title_input"><h4><%= f.label :title  %></h4>
      <%= f.text_field :title  %></li>
      <h4><li class="text_input"><%= f.label :text  %></h4>
      <%= f.text_area :text  %></li>
      <li class="text_submit"><%= f.submit "Ask" %></li>
    <% end %>
  </ul>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <%= render partial: 'votes/vote', locals: { votable: @question } %>
  <h3><%= @question.title %></h3>
  <p><%= @question.text %></p>
    <ul class="edit_buttons">
      <li></li>
      <% if !!session[:id] && session[:id] == @question.user_id %>
        <li>
          <%= button_to "Delete", question_path, {:method => :delete, :class => "deleteQuestionButton"} %>
        </li>
        <li><%= button_to "Edit", edit_question_path(@question), {:method => :get, :class => "editQuestionButton"} %>
        </li>
      <% end %>
    </ul>
  <span class="answer_button"><%= button_to "Answer", new_question_answer_path(@question), {:method => :get, :remote => true, :class => "answerButton"} %></span>

  <span class="comment_button"><%= button_to "comment", new_question_comment_path(@question), {:method => :get, :remote => true, :class => "commentButton"} %></span>

  <span class="question_user">Asked by: <span class="user"><%= link_to @question.user.username, user_path(@question.user) %></span></span>
</div>
<div class="question_comments">
  <p class="comments"><%= render partial: 'shared/comments', locals: {commentable: @question} %></p>
</div>

app/views/questions/edit.html.erb
<%= render 'shared/errors', :object => @question  %>
<%= render 'form', :object => @question  %>

app/views/questions/index.html.erb
<% if session[:id] %>
	<%= render 'form', :object => @question=Question.new  %>
<% else %>
	<%= render 'shared/login_button' %>
<% end %>

<div class="all_qs">
  <ul class="questions">
     <% @questions.each do |question| %>
      <li>
        <span class="vote_count"><%= question.vote_count %></span>
        <span class="question_link"><%= link_to question.title, question_path(question) %></span>
        <span class="question_user">Asked by: <span class="user"><%=link_to question.user.username, user_path(question.user) %></span></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/questions/new.html.erb
<%= render 'shared/errors', :object => @question  %>
<%= render 'form', :object => @question  %>

app/views/questions/show.html.erb
<%= render 'question' %>
<%= render 'answers/answer', :object => @question, :object => @answers %>

app/views/shared/_comments.html.erb
<div class="commentable">
  <ul>
    <li><h2>Comments </h2></li>
  <% commentable.comments.each do |comment| %>
  	<li><span class="opinion"><%= comment.opinion %></span> - <span class="username"><%=link_to comment.user.username, user_path(comment.user) %></span></li>
  <% end %>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% object.errors.full_messages.each do |error| %>
  <%= error %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

app/views/shared/_login:logout.html.erb
<% if session[:id] %>
    <li><%= link_to "Sign Out", session_path(session[:id]), method: "delete" %></li>
<% else %>
    <li><%= link_to "Log In", new_session_path%></li>
	<li><%= link_to "Sign Up", new_user_path %></li>
<% end %>

app/views/shared/_login_button.html.erb
<div class="login_or_signup">
  <ul>
  	<li><%= link_to "Log In", new_session_path, class: 'login_btn', :remote => true%></li>
    <li><span class="or">or</span></li>
  	<li><%= link_to "Sign Up", new_user_path, class: 'signup_btn', :remote => true %></li>
  </ul>
</div>
<br>

app/views/users/new.html.erb
<%= render 'shared/errors', :object => @user %>
<%= render 'shared/flash', :flash => flash %>
<div class="login_form">
  <ul>
    <%= form_for @user do |f| %>
      <li><h4 class="label"><%= f.label :username %></h4>
      <span class="input_field"><%= f.text_field :username %></span></li>
      <li><h4 class="label"><%= f.label :password %></h4>
      <span class="input_field"><%= f.password_field :password %></span></li>
      <li><h4 class="label"><%= f.label :password_confirmation %></h4>
      <span class="input_field"><%= f.password_field :password_confirmation %></span></li>
      <li> <span class="submit"><%= f.submit %><span></li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="user_profile">
  <ul>
    <li><span class="username"><h1><%= @user.username %></h1></span></li>
    <li><h3>Joined on <%= @user.created_at.to_date %></h3></li>
    <br>
    <li>Questions Asked:
      <% @user.questions.each do |question| %>
        <span class="q_a_link"><%= link_to question.title, question_path(question) %> </span>
      <% end  %>
    </li>
    <li>Answers to Questions:
      <% @user.answers.each do |answer| %>
        <span class="q_a_link"><%= link_to answer.question.title, question_path(answer.question) %></span>
        <% end %></li>
    <li>Reputation: <%=@user.reputation%></li>
  </ul>
</div>

app/views/votes/_vote.html.erb
<ul class="voting">
  <% if votable.class.name == "Question" %>
    <li><%= link_to image_tag('up.svg'), question_votes_path(votable, :up_down => 1 ), :method => :post %></li>
    <li class="count"><h6><%= votable.vote_count %></h6></li>
    <li><%= link_to image_tag('down.svg'), question_votes_path(votable, :up_down => -1 ), :method => :post %></li>
  <% else %>
    <li><%= link_to image_tag('up.svg'), answer_votes_path(votable, :up_down => 1 ), :method => :post %></li>
    <li class="count"><h6><%= votable.vote_count %></h6></li>
    <li><%= link_to image_tag('down.svg'), answer_votes_path(votable, :up_down => -1 ), :method => :post %></li>
  <% end %>
</ul>